---
title: "Bayesian estimates for diputados"
output: rmarkdown::html_vignette
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(quickcountmx)
cmdstanr::install_cmdstan(cores = 2, quiet = TRUE)
```


## Estimation and testing with 2021 results


Lower house estimates

```{r}
library(tidyverse)
```

```{r}
dip_muestra <- readr::read_delim("../data-raw/diputados/remesa-diputados-2021.txt", delim = "|") |> 
  mutate(CLAVE_CASILLA = paste0("'", str_pad(ID_ESTADO, 2, "left", "0"), 
                                str_pad(SECCION, 4, "left", "0"),
                                TIPO_CASILLA, 
                                str_pad(ID_CASILLA, 2, "left", "0"),
                                str_pad(EXT_CONTIGUA, 2, "left", "0"),
                                "'") ) |> 
  mutate(ESTRATO = paste(ID_ESTADO, ID_DISTRITO_FEDERAL)) 
computos <- readr::read_delim("../data-raw/diputados/diputaciones.csv", delim = "|",
                                 locale = locale(encoding = "Windows-1250"), skip = 5) |> 
  mutate(ESTRATO=paste(ID_ESTADO, ID_DISTRITO)) |> 
  mutate(no_casilla = row_number()) |> 
  mutate(urbana = ifelse(CASILLA == "Urbana", 1, 0)) |> 
  mutate(ln = ifelse(LISTA_NOMINAL_CASILLA == 0, 800, LISTA_NOMINAL_CASILLA))
prueba <- left_join(dip_muestra, computos |> select(CLAVE_CASILLA, NUM_ACTA_IMPRESO),
                    by = "CLAVE_CASILLA")
prueba |> count(NUM_ACTA_IMPRESO)
dip_muestra <- dip_muestra |>  left_join(computos |> select(CLAVE_CASILLA, no_casilla), by = "CLAVE_CASILLA")
```

```{r}
coaliciones <- c("PAN", "PRI", "PRD", "PT", "PVEM", "MC", "MORENA", "PES", "RSP", 
"FPM", "PAN_PRI_PRD", "PAN_PRI", "PAN_PRD", "PRI_PRD", "PVEM_PT_MORENA", 
"PVEM_PT", "PVEM_MORENA", "PT_MORENA", "CI1", "CNR")
coaliciones_tbl <- tibble(coalicion = coaliciones, 
  partidos = str_split(coaliciones, "_")) |> 
  mutate(num_partidos = map_int(partidos, length)) |> 
  mutate(partidos = map(partidos, ~ unlist(.x))) |> 
  unnest(partidos)
coaliciones_tbl
```

```{r}
partidos <- c(coaliciones[1:10], "CI1", "CNR", "NULOS")
partidos
dip_muestra_agr <- dip_muestra |> 
  pivot_longer(cols = all_of(coaliciones), names_to = "coalicion", values_to = "votos") |> 
  left_join(coaliciones_tbl, by = "coalicion", relationship = "many-to-many") |> 
  mutate(votos_distrib = votos / num_partidos) |> 
  select(-coalicion, -num_partidos, -votos) |> 
  group_by(across(c(-votos_distrib))) |> 
  summarise(votos = round(sum(votos_distrib)), .groups = "drop") |> 
  pivot_wider(names_from = partidos, values_from = votos)
```

We setup a small run (small sample and too few sampling iterations) to get inv_metric, and a larger sample to test:

```{r}
set.seed(91)
muestra_1 <- sample_n(dip_muestra_agr, 1000)
muestra_prev <- sample_n(muestra_1, 300)
```

```{r}
fit_estimates_1 <- hb_estimation(muestra_prev, stratum = ESTRATO,
                      id_station = no_casilla,
                      sampling_frame =  computos,
                      model = "mlogit-corr",
                      parties = all_of(partidos),
                      covariates = c(urbana),
                      chains = 4, 
                      num_warmup = 400,
                      num_iter = 100, 
                      adapt_delta = 0.9,
                      max_treedepth = 11,
                      nominal_max = 800,
                      prop_obs = 0.05,
                      seed = 123, results_strata = TRUE)
```





```{r}
inv_metric_1 <- fit_estimates_1$inv_metric
```

```{r}
fit_estimates <- hb_estimation(muestra_1, stratum = ESTRATO,
                      id_station = no_casilla,
                      sampling_frame =  computos,
                      model = "mlogit-corr",
                      parties = all_of(partidos),
                      covariates = c(urbana),
                      chains = 3, 
                      num_warmup = 200,
                      num_iter = 200, 
                      adapt_delta = 0.95,
                      max_treedepth = 11,
                      nominal_max = 800,
                      prop_obs = 0.6,
                      inv_metric = inv_metric_1,
                      seed = 1234, results_strata = TRUE)
```


```{r}
#| output: asis
fit_estimates$estimates |> mutate(across(where(is.numeric), ~round(.x, 4))) |> 
  as_tibble()
```

```{r}
estratos_sims <- fit_estimates$strata_draws
estratos_sims |> filter(tipo == "prop_votos_strata") |> pull(partido_nom) |> unique()
```

```{r}
estratos_sims
```

```{r}
# Asignar por mayoría (sin tomar en cuenta qué dip se le cuenta a cada partido,
# esto esta mal)
resumen_asignacion_mayoria <- estratos_sims |>
  filter(tipo == "prop_votos_strata") |>
  filter(!(partido_nom %in% c("NULOS", "CNR"))) |> 
  group_by(sims, strata) |> 
  mutate(ganador = (prop == max(prop))) |> 
  group_by(sims, partido_nom) |> 
  summarise(ganados = sum(ganador)) |> 
  group_by(partido_nom) 
resumen_asignacion_mayoria |> 
  summarise(inf = floor(quantile(ganados, 0.025)), sup = ceiling(quantile(ganados, 0.975))) |> 
  arrange(desc(inf))
```

Proporcional sin corrección por sobrerrepresentación:

```{r}
# está mal porque falta sobrerrepresentación
asignacion_prop <- fit_estimates$total_draws |> filter(tipo == "prop_votos") |> 
  filter(!partido_nom %in% c("NULOS", "CNR","CI1")) |>
  mutate(prop = ifelse(prop < 0.03, 0, prop)) |>
  group_by(sims) |> 
  mutate(asignados_prop = floor(200 * prop / sum(prop)))
asignacion_prop |> 
  group_by(partido_nom) |> 
  summarise(inf = floor(quantile(asignados_prop, 0.025)), sup = ceiling(quantile(asignados_prop, 0.975))) |> 
  arrange(desc(inf))
```

Corregir sobre representacion

```{r}
asignacion_may_prop <- asignacion_mayoria |> full_join(asignacion_prop |> select(-tipo, -id_partido), 
                                                       by = c("sims", "partido_nom")) |> 
  mutate(ganados = ifelse(is.na(ganados), 0, ganados)) |>
  mutate(prop = ifelse(is.na(prop), 0, prop)) |>
  mutate(asignados_prop = ifelse(is.na(asignados_prop), 0, asignados_prop)) |> 
  mutate(total = ganados + asignados_prop) |>
  group_by(sims) |> 
  mutate(total_camara_prop = total/sum(total)) |> 
  mutate(sobre_rep = total_camara_prop - prop) |> 
  mutate(resto = ifelse(sobre_rep > 0.08, 500 * (sobre_rep - 0.08), 0)) |> 
  group_by(sims) |> 
  mutate(prop_nuevas = ifelse(resto > 0, 0, prop)) |> 
  mutate(asignados_nuevos = sum(resto, na.rm = TRUE)*prop_nuevas/sum(prop_nuevas)) |> 
  mutate(total_final = ifelse(resto>0, 500 * (prop + 0.08), total + asignados_nuevos))
```


```{r}
asignacion_may_prop |> 
  group_by(partido_nom) |> 
  summarise(inf = floor(quantile(total_final, 0.025, na.rm = TRUE)), 
            sup = ceiling(quantile(total_final, 0.975, na.rm = TRUE))) |> 
  arrange(desc(inf))
```




