---
title: "Monitor de remesas"
output: html_document
lang: es
format: 
  html:
    embed-resources: true
---

```{r, echo=FALSE,message=FALSE}
library(tidyverse)
library(kableExtra)
```

```{r, echo=FALSE,message=FALSE}
#path_estimaciones <- "/home/rstudio/cotecora/estimaciones/"
path_estimaciones <- "~/Documents/pruebas-script"
path_estimaciones <- "/Volumes/estimaciones/"
estimaciones_files <- list.files(path_estimaciones, full.names = TRUE,
                                 recursive = TRUE, include.dirs = FALSE, 
                                 pattern = "*csv")
modelos <- c("hb","compulsado","razon")
```

Analizamos datos del último corte:

```{r, echo=FALSE,message=FALSE, include = TRUE}
#path_cortes <- "/home/rstudio/cotecora/cortes/"
path_cortes <- "/Volumes/cortes/"

cortes_files <- list.files(
  path_cortes, 
  full.names = TRUE,
  recursive = TRUE,
  include.dirs = FALSE, 
  pattern = "REMESAS.*\\.txt$"
)

corte_mas_reciente_file <- cortes_files[which.max(file.info(cortes_files)$mtime)]
corte_mas_reciente_file
```

```{r, echo=FALSE,message=FALSE}
corte_mas_reciente <- read.table(corte_mas_reciente_file, 
                                 header = TRUE, 
                                 sep = "|",
                                 stringsAsFactors = FALSE) |>
  select(c("CLAVE_CASILLA", "ID_ESTADO", 
    "PERSONAS_VOTANTES",
    "ID_DISTRITO", 
    "PERSONAS_VOTANTES",
    "ARE")) |>
  rename(ID_DISTRITO_FEDERAL = ID_DISTRITO)
```

```{r, echo=FALSE,message=FALSE}
marco_2025 <- readRDS("../data-raw/marco_2025.rds") |>
  select(-FECHA_HORA) |>
  mutate(CLAVE_CASILLA = gsub("'","",CLAVE_CASILLA))

corte_mas_reciente <- corte_mas_reciente |>
  left_join(marco_2025, by = c("CLAVE_CASILLA", "ID_ESTADO",
                               "ID_DISTRITO_FEDERAL")) 
```

### ¿Qué estados aún no tienen datos?

```{r, echo=FALSE,message=FALSE}
tab_estados_df_dje <- marco_2025 |>
  select(ID_ESTADO, NOMBRE_ESTADO, ID_DISTRITO_FEDERAL, DISTRITO_JUDICIAL_ELECTORAL, CIRCUITO_JUDICIAL) |>
  distinct() |>
  arrange(ID_ESTADO, ID_DISTRITO_FEDERAL)
```

```{r, echo=FALSE,message=FALSE}
tab_estados_df_dje |>
  anti_join(corte_mas_reciente |> distinct(ID_ESTADO), by = "ID_ESTADO") |>
  arrange(ID_ESTADO) |>
  distinct(ID_ESTADO, NOMBRE_ESTADO) |>
  kable()
```

### Muestra por estrato

```{r, echo=FALSE,message=FALSE}
asignacion <- read_csv("../data-raw/asignacion_estratos_2025.csv") |>
  rename(muestra_esperada = n, estrato = id_dje)
```

```{r, echo=FALSE,message=FALSE, include = TRUE}
tabla_muestra <- corte_mas_reciente |>
  group_by(ID_ESTADO, estrato) |>
  summarise(
    muestra_recibida = n(),
    .groups = "drop"
  ) |>
  right_join(asignacion, by = "estrato") |>
  mutate(muestra_recibida = ifelse(is.na(muestra_recibida), 0, muestra_recibida)) |>
  arrange(ID_ESTADO, estrato) |>
  left_join(marco_2025 |> 
              select(ID_ESTADO, NOMBRE_ESTADO) |> 
              distinct(), by = "ID_ESTADO") |>
  select(NOMBRE_ESTADO, estrato, muestra_esperada, muestra_recibida)

# Primero genera la columna con colores
colores <- tabla_muestra |> 
  mutate(color = case_when(
    muestra_recibida < 10 ~ "red",
    muestra_recibida >= floor(muestra_esperada * 0.9) ~ "green",
    TRUE ~ "black"
  )) |> 
  pull(color)

# Ahora genera la tabla usando esos colores
tabla_muestra |>  
  kable(
    col.names = c("Estado", "Estrato", "Muestra esperada", "Muestra recibida"),
    booktabs = TRUE
  ) |>
  kable_styling() |>
  column_spec(4, color = colores)
```

```{r, echo=FALSE,message=FALSE}
corte_mas_reciente |>
  arrange(PERSONAS_VOTANTES) |>
  mutate(orden = row_number()) |>
  ggplot(aes(x = orden, y = PERSONAS_VOTANTES)) +
  geom_point(alpha = 0.7, size = 2, color = "#2C7BB6") +
  labs(title = "Distribución ordenada de los votos totales por casilla",
       x = "Casillas ordenadas",
       y = "Votos totales") +
  theme_minimal()
```

```{r, echo=TRUE,message=FALSE}
lim_max <- 1000
corte_mas_reciente |>
  arrange(desc(PERSONAS_VOTANTES)) |>
  filter(PERSONAS_VOTANTES > lim_max) |>
  select(CLAVE_CASILLA, ID_ESTADO, ID_DISTRITO_FEDERAL, PERSONAS_VOTANTES, TIPO_CASILLA)
```

```{r, echo=TRUE,message=FALSE}
lim_min <- 5
corte_mas_reciente |>
  arrange(desc(PERSONAS_VOTANTES)) |>
  filter(PERSONAS_VOTANTES < lim_min) |>
  select(CLAVE_CASILLA, ID_ESTADO, ID_DISTRITO_FEDERAL, PERSONAS_VOTANTES, TIPO_CASILLA)
```

```{r, echo=FALSE,message=FALSE}
corte_mas_reciente |>
  mutate(participacion = 100 * PERSONAS_VOTANTES / LISTA_NOMINAL_CASILLA) |>
  arrange(participacion) |>
  mutate(orden = row_number()) |>
  ggplot(aes(x = orden, y = participacion)) +
  geom_point(alpha = 0.7, size = 2, color = "darkgray") +
  labs(title = "Distribución ordenada de porcentajes de participación por casilla",
       x = "Casillas ordenadas",
       y = "Participación (%)") +
  theme_minimal()
```

```{r, echo=FALSE, include = FALSE, message = FALSE}
revisar_anomalias <- function(datos, umbral_participacion) {
  datos <- datos |> 
    mutate(ln = ifelse(TIPO_CASILLA == "S" & LISTA_NOMINAL_CASILLA == 0, 
                       1000, LISTA_NOMINAL_CASILLA)) |>
    mutate(participacion = 100 * PERSONAS_VOTANTES / ln)
  
  anomalias <- datos |>
    filter(participacion > umbral_participacion) |>
    arrange(desc(participacion)) |>
    select(participacion, ln, PERSONAS_VOTANTES, CLAVE_CASILLA, 
           ID_ESTADO, ID_DISTRITO_FEDERAL, TIPO_CASILLA)
  
  if (nrow(anomalias) > 0) {
    message("⚠️ Casillas atípicas detectadas con participación superior a ", umbral_participacion, "%:")
    print(anomalias |> kableExtra::kable())
  } else {
    message("✅ No se encontraron casillas atípicas con participación superior a ", umbral_participacion, "%.")
  }
  return()
}
```

```{r, echo=FALSE, include = TRUE}
anomalias_detectadas <- revisar_anomalias(corte_mas_reciente, 90)
anomalias_detectadas 
```

# Estimaciones de participación

```{r, echo=FALSE,message=FALSE, include = TRUE}
get_df <- function(modelo, estimaciones_files){
  get_fdate <- function(x){
    x <- as.character(x)
    nx <- as.POSIXct(paste0(
      substr(x,1,2)," ",substr(x,3,4),":",substr(x,5,6)),format = "%d %H:%M"
      )
  }
  files_modelo <- estimaciones_files[grepl(modelo, estimaciones_files, fixed = TRUE)]
  estimaciones_modelo <- files_modelo |>
    map_df(~ read_csv(.x) |> mutate(method = modelo)) |>
    select("PART", "LMU", method, R, muestra, p_muestra, num_estratos) |>
    mutate(fecha = R) |>
    mutate_at(vars(fecha), get_fdate) |>
    group_by(method) |>
      mutate(LMU = dplyr::case_when(
      LMU == 0 ~ "inf",
      LMU == 1 ~ "median",
      LMU == 2 ~ "sup")) |>
      tidyr::pivot_wider(names_from = LMU, values_from = "PART") 
    estimaciones_modelo
}

get_df_compulsado <- function(modelo, estimaciones_files){
  get_fdate <- function(x){
    x <- as.character(x)
    nx <- as.POSIXct(
  paste0("2025-", substr(x, 1, 2), "-", substr(x, 3, 4), " ",
         substr(x, 5, 6), ":", substr(x, 7, 8)),
  format = "%Y-%m-%d %H:%M"
)
  }
  files_modelo <- estimaciones_files[grepl(modelo, estimaciones_files, fixed = TRUE)]
  estimaciones_modelo <- files_modelo |>
    map_df(~ read_csv(.x) |> mutate(method = modelo)) |>
    select("PART", "LMU", method, R, muestra, p_muestra, num_estratos) |>
    mutate(fecha = R) |>
    mutate_at(vars(fecha), get_fdate) |>
    group_by(method) |>
      mutate(LMU = dplyr::case_when(
      LMU == 0 ~ "inf",
      LMU == 1 ~ "median",
      LMU == 2 ~ "sup")) |>
      tidyr::pivot_wider(names_from = LMU, values_from = "PART") 
    estimaciones_modelo
}

estimaciones_hb <- get_df("hb", estimaciones_files) |> select(-R)
estimaciones_razon <- get_df("razon", estimaciones_files) |> select(-R)
estimaciones_compulsado <- get_df_compulsado("compulsado", estimaciones_files) |> select(-R)

estimaciones_tbl <- rbind(estimaciones_hb, estimaciones_razon, estimaciones_compulsado)
```
```{r , echo=FALSE, fig.width = 8, include = TRUE, warning = FALSE}
ggplot(estimaciones_tbl, aes(x = fecha, y = p_muestra)) +
  geom_line(color = "#2171b5", linewidth = 1) +
  geom_point(color = "#2171b5", alpha = 0.6, size = 2) +
  scale_x_datetime(
    breaks = estimaciones_tbl$fecha,  
    date_labels = "%b %d\n%H:%M"
  ) +
  labs(
    title = "Evolución de p_muestra a lo largo del tiempo",
    x = "Fecha y hora",
    y = "p_muestra"
  ) +
  theme_minimal(base_family = "Helvetica") +
  theme(
    plot.title = element_text(face = "bold", size = 16, hjust = 0),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title = element_text(size = 12),
    axis.text = element_text(size = 10),
    panel.grid.minor = element_blank()
  )
```

```{r , echo=FALSE, fig.width = 8, include = TRUE, warning = FALSE}
ggplot(estimaciones_tbl, aes(x = fecha, y = median, color = method, fill = method)) +
  geom_line(linewidth = 1) +
  geom_ribbon(aes(ymin = inf, ymax = sup), alpha = 0.2, color = NA) +
  facet_wrap(~ method) +
  labs(
    x = "Hora",
    y = "Porcentaje",
    color = "Método",
    fill = "Método"
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    strip.background = element_rect(fill = "gray90"),
    panel.grid.minor = element_blank()
  )
```

```{r , echo=FALSE, fig.width = 8, include = TRUE, warning = FALSE}
ggplot(estimaciones_tbl, aes(x = p_muestra, y = median, color = method, fill = method)) +
  geom_line(linewidth = 1) +
  geom_ribbon(aes(ymin = inf, ymax = sup), alpha = 0.2, color = NA) +
  facet_wrap(~ method) +
  labs(
    x = "Porcentaje muestra recibida",
    y = "Porcentaje part",
    color = "Método",
    fill = "Método"
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    strip.background = element_rect(fill = "gray90"),
    panel.grid.minor = element_blank()
  )
```




