---
title: "Ejemplo de extracción de muestras y estimación"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{estimador-razon}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(quickcountmx)
library(dplyr)
library(tidyr)
```

The final computations can calculated as follows: 

```{r}
data("conteo_2018")
conteo_2018 <- conteo_2018 %>% 
  filter(TOTAL_VOTOS_CALCULADOS!= 0) %>% 
  filter(ID_DISTRITO != 0) %>% 
  mutate(distrito_f = interaction(ID_ESTADO, ID_DISTRITO))
final_computos <- conteo_2018 %>% 
  select(any_of(c("AMLO", "JAMK", "RAC", "CAND_IND_02", "TOTAL_VOTOS_CALCULADOS"))) %>%
  summarise(across(is.numeric, ~ sum(.x, na.rm = TRUE))) %>% 
  mutate(across(is.numeric, ~ .x / TOTAL_VOTOS_CALCULADOS))%>% 
  pivot_longer(cols = everything(), names_to = "candidato", values_to = "prop")
final_computos
```

To select a proportional sample

```{r}
# select sample
sample <- select_sample_prop(conteo_2018, 
                             stratum = distrito_f, frac = 0.01, seed = 100)
nrow(sample)
```


Ratio estimates:

```{r}
stratification <- conteo_2018 %>% 
  group_by(distrito_f) %>% 
  count()
estimates <- ratio_estimation(sample, stratum = distrito_f,
                              data_stratum = stratification, n_stratum = n,
                              B = 20, seed = 123,
                              parties = any_of(c("AMLO", "JAMK", "RAC", 
                                                 "CAND_IND_01", "CAND_IND_02" ,
                                                 "VN", "CNR")))
estimates %>% mutate(across(where(is.numeric), ~round(.x, 2)))
```

