---
title: "Sample selection, censored samples and ratio estimates"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ratio-estimation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(quickcountmx)
```


```{r}
library(dplyr)
library(tidyr)
data("conteo_2018")
nrow(conteo_2018)
```


The final computations can calculated as follows: 

```{r}
conteo_2018 <- conteo_2018 %>% 
  filter(TOTAL_VOTOS_CALCULADOS!= 0) %>% 
  filter(ID_DISTRITO != 0) %>% 
  mutate(distrito_f = interaction(ID_ESTADO, ID_DISTRITO)) |> 
  mutate(LISTA_NOMINAL = LISTA_NOMINAL_CASILLA)
final_computos <- conteo_2018 %>% 
  select(any_of(c("AMLO", "JAMK", "RAC", "CAND_IND_02", "TOTAL_VOTOS_CALCULADOS"))) %>%
  summarise(across(where(is.numeric), ~ sum(.x, na.rm = TRUE))) %>% 
  mutate(across(where(is.numeric), ~ .x / TOTAL_VOTOS_CALCULADOS))%>% 
  pivot_longer(cols = everything(), names_to = "candidato", values_to = "prop")
final_computos
```

To select a proportional sample

```{r}
# select sample
sample <- select_sample_prop(conteo_2018, 
                             stratum = distrito_f, frac = 0.01, seed = 100)
nrow(sample)
```


Ratio estimates:

```{r}
stratification <- conteo_2018 %>% 
  group_by(distrito_f) %>% 
  count()
estimates <- ratio_estimation(sample, stratum = distrito_f,
                              data_stratum = stratification, n_stratum = n,
                              B = 20, seed = 123,
                              parties = any_of(c("AMLO", "JAMK", "RAC", 
                                                 "CAND_IND_01", "CAND_IND_02" ,
                                                 "VN", "CNR")))
estimates %>% mutate(across(where(is.numeric), ~round(.x, 2)))
```
We can also work with a time censored sample, simulating arrival times

```{r}
data("arrivals_tbl")
states <- unique(arrivals_tbl$state_abbr)
model_national <- fit_model(arrivals_tbl, states)
sims_national <- simulate_arrivals(1, model_national, new_data_tbl = conteo_2018, hour_censoring = Inf)
```

```{r}
data_tbl <- sims_national %>% left_join(conteo_2018 %>% select(CLAVE_CASILLA, distrito_f, 
      any_of(c("AMLO", "JAMK", "RAC", "CAND_IND_02", "CNR", "VN"))),
    by = "CLAVE_CASILLA")
data_tbl <- data_tbl %>% left_join(conteo_2018 %>% select(CLAVE_CASILLA, LISTA_NOMINAL))
# select sample
sample <- select_sample_prop(data_tbl, stratum = distrito_f, frac = 0.01, seed = 100)
nrow(sample)
```

Full sample estimates:

```{r}
estimates <- ratio_estimation(sample, stratum = distrito_f,
                              data_stratum = stratification, n_stratum = n,
                              B = 100, seed = 123,
                              parties = any_of(c("AMLO", "JAMK", "RAC", 
                                                 "CAND_IND_01", "CAND_IND_02" ,
                                                 "VN", "CNR")))
estimates %>% mutate(across(where(is.numeric), ~round(.x, 2)))
```

Time censored data:

```{r}
sample_censored <- sample %>% filter(time < 3)
nrow(sample_censored)
estimates <- ratio_estimation(sample_censored, 
                              stratum = distrito_f,
                              data_stratum = stratification, n_stratum = n,
                              B = 100, seed = 123,
                              parties = any_of(c("AMLO", "JAMK", "RAC", 
                                                 "CAND_IND_01", "CAND_IND_02" ,
                                                 "VN", "CNR")))
estimates %>% mutate(across(where(is.numeric), ~round(.x, 2)))
```


## Estimation for seats of diputados

Prepare data

```{r}
set.seed(9898)
# built with info from INE, states in which strata parties compete in coalitions and
# the party to which the candidate belongs
assignment_tbl <- readr::read_csv("asignacion-coaliciones.csv") |> 
  rename(party = nombre_partido) |> mutate(strata = paste(ID_ENTIDAD, DISTRITO, sep = "."))
  
sample_diputados <- readr::read_delim("REMESAS0400062235.txt", 
    delim = "|", escape_double = FALSE, trim_ws = TRUE, 
    skip = 1) |> 
  mutate(distrito_f = paste(ID_ESTADO, ID_DISTRITO_FEDERAL, sep = "."))

coalitions_tbl <- tibble(coalition = names(sample_diputados)[16:36]) |> 
  mutate(party = coalition) |> 
  tidyr::separate_longer_delim(party, delim = "_")

n_strata_tbl <- sample_diputados |> 
  group_by(distrito_f) |> 
  count(name = "n_strat")
```

Bootstrap replicates:

```{r}

sample_diputados_miss <- sample_diputados |> 
  filter(!(ID_ESTADO == 1 & ID_DISTRITO_FEDERAL == 1))
replicates <- bootstrap_diputados(sample_diputados_miss, stratum = distrito_f,
                                  stratum_tbl = n_strata_tbl, n_stratum = n_strat,
                                  coalitions_tbl = coalitions_tbl, 
                                  B = 20, seed = 12,
                                  samples_table = TRUE)
```

Computing majority seats

```{r}
majority_seats_rep <- assign_majority(replicates$strata_tbl, assignment_tbl , 
                party_name = party, candidate_name = candidato) 
majority_seats_rep |>
  group_by(candidate) |> 
  summarise(inf = quantile(n_seats_maj, 0.02), 
            sup = quantile(n_seats_maj, 0.98))

```
Total seats,

```{r}
assign_seats_rep <- assign_all_seats(replicates, assignment_tbl)

glimpse(assign_seats_rep)

assign_seats_rep |> 
  group_by(party) |> 
  summarise(inf = quantile(n_seats_total, 0.02), 
            sup = quantile(n_seats_total, 0.98)) |>
  arrange(-inf)  
  
```
All steps in a single function:

```{r}
estimates <- ratio_estimation_diputados(sample_diputados, stratum = distrito_f,
                                        stratum_tbl = n_strata_tbl, 
                                        n_stratum = n_strat,
                                        coalitions_tbl = coalitions_tbl, 
                                        assignment_tbl = assignment_tbl,
                                        B = 20, seed = 12)
estimates |> 
  mutate(across(where(is.double), ~round(., 3)))
```

